// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sistema_de_Personagens.Data;

#nullable disable

namespace Sistema_de_Personagens.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Sistema_de_Personagens.Models.Personagem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Nivel")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.HasKey("Id");

                    b.ToTable("TabelaPersonagem");

                    b.HasDiscriminator<string>("Tipo").HasValue("Personagem");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Sistema_de_Personagens.Models.Guerreiro", b =>
                {
                    b.HasBaseType("Sistema_de_Personagens.Models.Personagem");

                    b.HasDiscriminator().HasValue("Guerreiro");
                });

            modelBuilder.Entity("Sistema_de_Personagens.Models.Mago", b =>
                {
                    b.HasBaseType("Sistema_de_Personagens.Models.Personagem");

                    b.HasDiscriminator().HasValue("Mago");
                });
#pragma warning restore 612, 618
        }
    }
}
