// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sistema_de_Animais.Data;

#nullable disable

namespace Sistema_de_Animais.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Sistema_de_Animais.Models.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.HasKey("Id");

                    b.ToTable("TabelaAnimal");

                    b.HasDiscriminator<string>("Tipo").HasValue("Animal");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Sistema_de_Animais.Models.Elefante", b =>
                {
                    b.HasBaseType("Sistema_de_Animais.Models.Animal");

                    b.HasDiscriminator().HasValue("Elefante");
                });

            modelBuilder.Entity("Sistema_de_Animais.Models.Leao", b =>
                {
                    b.HasBaseType("Sistema_de_Animais.Models.Animal");

                    b.HasDiscriminator().HasValue("Leao");
                });
#pragma warning restore 612, 618
        }
    }
}
